In [1]:
from dotenv import load_dotenv
import os
import finnhub
import pandas as pd
import numpy as np

from alpaca.data.historical import StockHistoricalDataClient
from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame
from alpaca.trading.client import TradingClient
import plotly.express as px
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [2]:
load_dotenv()

KEY = os.getenv("key")
SECRET = os.getenv("secret")

In [3]:
client = StockHistoricalDataClient(KEY, SECRET)

request = StockBarsRequest(
    symbol_or_symbols = "NVDA",
    timeframe = TimeFrame.Day,
    start = "2026-01-01",
)
bars = client.get_stock_bars(request)

df = bars.df

df

                                     open      high     low   close  \
symbol timestamp
NVDA   2026-01-02 05:00:00+00:00  189.835  192.9299  188.26  188.85
       2026-01-05 05:00:00+00:00  191.760  193.6300  186.15  188.12
       2026-01-06 05:00:00+00:00  190.520  192.1740  186.82  187.24
       2026-01-07 05:00:00+00:00  188.570  191.3700  186.56  189.11
       2026-01-08 05:00:00+00:00  189.110  189.5500  183.71  185.04
...                                   ...       ...     ...     ...
       2026-09-08 04:00:00+00:00  233.110  233.7100  224.85  225.73
       2026-09-09 04:00:00+00:00  225.275  226.1800  223.46  223.67
       2026-09-10 04:00:00+00:00  220.525  220.9900  217.20  218.36
       2026-09-11 04:00:00+00:00  221.235  222.0000  218.15  218.29
       2026-09-14 04:00:00+00:00  211.240  212.3900  208.93  212.20

                                       volume  trade_count        vwap
symbol timestamp
NVDA   2026-01-02 05:00:00+00:00  148240462.0    2260604.0  189.912199
       2026-01-05 05:00:00+00:00  182965768.0    2574019.0  188.757392
       2026-01-06 05:00:00+00:00  176862604.0    2519447.0  189.058048
       2026-01-07 05:00:00+00:00  153543174.0    2292255.0  189.527040
       2026-01-08 05:00:00+00:00  172457048.0    2521746.0  185.358816
...                                       ...          ...         ...
       2026-09-08 04:00:00+00:00  123863958.0    2405736.0  227.183114
       2026-09-09 04:00:00+00:00   83765394.0    1827357.0  224.230606
       2026-09-10 04:00:00+00:00  106720602.0    2202079.0  218.423135
       2026-09-11 04:00:00+00:00   90036579.0    2013738.0  219.556789
       2026-09-14 04:00:00+00:00   77067681.0    1987583.0  210.863471

[175 rows x 7 columns]

In [4]:
#Setter opp klienten

finnhub_client = finnhub.Client(api_key=os.getenv("finnhub_key"))

#Henter alle grunnleggende data for NVIDIA
data = finnhub_client.company_basic_financials("NVDA", "all")
quarterly_series = data["series"]["quarterly"]

print(data)
#Dette gir meg en stor dictonary med masse metrics under data["metric"]. f.eks peNormalizedAnnual, roeTTM, netProfitMarginTTM osv.

{'metric': {'10DayAverageTradingVolume': 125.74631, '13WeekPriceReturnDaily': 8.9163, '26WeekPriceReturnDaily': 19.5127, '3MonthADReturnStd': 40.5757, '3MonthAverageTradingVolume': 144.10357, '52WeekHigh': 236.54, '52WeekHighDate': '2026-05-14', '52WeekLow': 164.27, '52WeekLowDate': '2026-03-30', '52WeekPriceReturnDaily': 23.2093, '5DayPriceReturnDaily': -5.2396, 'assetTurnoverAnnual': 1.0442, 'assetTurnoverTTM': 1.2788, 'beta': 2.2238405, 'bookValuePerShareAnnual': 6.4719, 'bookValuePerShareQuarterly': 9.4829, 'bookValueShareGrowth5Y': 56.87, 'capexCagr5Y': 39.89, 'cashFlowPerShareAnnual': 3.9778, 'cashFlowPerShareQuarterly': 5.2597, 'cashFlowPerShareTTM': 8.20683, 'cashPerSharePerShareAnnual': 2.5739, 'cashPerSharePerShareQuarterly': 4.1152, 'currentDividendYieldTTM': 0.1288, 'currentEv/freeCashFlowAnnual': 54.5297, 'currentEv/freeCashFlowTTM': 41.5076, 'currentRatioAnnual': 3.9053, 'currentRatioQuarterly': 4.5889, 'dividendGrowthRate5Y': 20.05, 'dividendIndicatedAnnual': 1, 'dividendPerShareAnnual': 0.0399, 'dividendPerShareTTM': 0.2795, 'dividendYieldIndicatedAnnual': 0.03349, 'ebitdPerShareAnnual': 5.4349, 'ebitdPerShareTTM': 8.2446, 'ebitdaCagr5Y': 88.29, 'ebitdaInterimCagr5Y': 88.37, 'enterpriseValue': 5271712, 'epsAnnual': 4.8979, 'epsBasicExclExtraItemsAnnual': 4.8979, 'epsBasicExclExtraItemsTTM': 7.9108, 'epsExclExtraItemsAnnual': 4.8979, 'epsExclExtraItemsTTM': 7.9108, 'epsGrowth3Y': 204.08, 'epsGrowth5Y': 95.27, 'epsGrowthQuarterlyYoy': 128.21, 'epsGrowthTTMYoy': 125.15, 'epsInclExtraItemsAnnual': 4.8979, 'epsInclExtraItemsTTM': 7.9108, 'epsNormalizedAnnual': 4.8979, 'epsTTM': 7.9108, 'evEbitdaTTM': 26.2085, 'evRevenueTTM': 17.4002, 'focfCagr5Y': 83.13, 'forwardPE': 18.10034, 'forwardPEG': 0.34983, 'grossMargin5Y': 68.54, 'grossMarginAnnual': 73.15, 'grossMarginTTM': 74.67, 'inventoryTurnoverAnnual': 3.6829, 'inventoryTurnoverTTM': 3.2975, 'longTermDebt/equityAnnual': 0.0475, 'longTermDebt/equityQuarterly': 0.1413, 'marketCapitalization': 5260789, 'monthToDatePriceReturnDaily': -1.1278, 'netIncomeEmployeeAnnual': 2.8587, 'netIncomeEmployeeTTM': 4.5924, 'netInterestCoverageAnnual': 29.0975, 'netInterestCoverageTTM': 75.6607, 'netMarginGrowth5Y': 16.44, 'netProfitMargin5Y': 42.54, 'netProfitMarginAnnual': 55.6, 'netProfitMarginTTM': 63.66, 'operatingMargin5Y': 45.98, 'operatingMarginAnnual': 60.38, 'operatingMarginTTM': 65.17, 'payoutRatioAnnual': 0.81, 'payoutRatioTTM': 3.51, 'pb': 22.9745, 'pbAnnual': 28.8075, 'pbQuarterly': 20.768, 'pcfShareAnnual': 51.2158, 'pcfShareTTM': 39.1544, 'peAnnual': 43.8154, 'peBasicExclExtraTTM': 27.2751, 'peExclExtraAnnual': 274.2091, 'peExclExtraTTM': 27.2751, 'peInclExtraTTM': 27.2751, 'peNormalizedAnnual': 43.8154, 'peTTM': 27.2751, 'pegTTM': 0.57728, 'pfcfShareAnnual': 54.4167, 'pfcfShareTTM': 41.4216, 'pretaxMargin5Y': 47.57, 'pretaxMarginAnnual': 65.5, 'pretaxMarginTTM': 75.83, 'priceRelativeToS&P50013Week': 3.5595, 'priceRelativeToS&P50026Week': 6.8304, 'priceRelativeToS&P5004Week': -1.499, 'priceRelativeToS&P50052Week': 6.9905, 'priceRelativeToS&P500Ytd': 4.9665, 'psAnnual': 24.3625, 'psTTM': 17.3641, 'ptbvAnnual': 29.426, 'ptbvQuarterly': 21.0435, 'quickRatioAnnual': 3.1409, 'quickRatioQuarterly': 3.7757, 'receivablesTurnoverAnnual': 7.0188, 'receivablesTurnoverTTM': 6.6684, 'revenueEmployeeAnnual': 5.1414, 'revenueEmployeeTTM': 7.2135, 'revenueGrowth3Y': 100.05, 'revenueGrowth5Y': 66.9, 'revenueGrowthQuarterlyYoy': 105.85, 'revenueGrowthTTMYoy': 83.38, 'revenuePerShareAnnual': 8.8088, 'revenuePerShareTTM': 12.4756, 'revenueShareGrowth5Y': 67.72, 'roa5Y': 40.26, 'roaRfy': 58.06, 'roaTTM': 81.41000000000001, 'roe5Y': 58.77, 'roeRfy': 76.33, 'roeTTM': 110.11, 'roi5Y': 50.22, 'roiAnnual': 72.43, 'roiTTM': 101.59, 'tangibleBookValuePerShareAnnual': 6.3359, 'tangibleBookValuePerShareQuarterly': 9.3588, 'tbvCagr5Y': 61.18, 'totalDebt/totalEquityAnnual': 0.0538, 'totalDebt/totalEquityQuarterly': 0.1457, 'yearToDatePriceReturnDaily': 17.0456}, 'metricType': 'all', 'series': {'annual': {'bookValue': [{'period': '2026-01-25', 'v': 157293}, {'period': '2025-01-26', 'v': 79327}, {'period': '2024-01-28', 'v': 42978}, {'period': '2023-01-29', 'v': 22101}, {'period': '2022-01-30', 'v': 26612}, {'period': '2021-01-31', 'v': 16893}, {'period': '2020-01-26', 'v': 12204}, {'period': '2019-01-27', 'v': 9342}, {'period': '2018-01-28', 'v': 7471}, {'period': '2017-01-29', 'v': 5762}, {'period': '2016-01-31', 'v': 4469}, {'period': '2015-01-25', 'v': 4418}, {'period': '2014-01-26', 'v': 4456.398}, {'period': '2013-01-27', 'v': 4827.703}, {'period': '2012-01-29', 'v': 4145.724}, {'period': '2011-01-30', 'v': 3181.462}, {'period': '2010-01-31', 'v': 2665.14}, {'period': '2009-01-25', 'v': 2394.652}, {'period': '2008-01-27', 'v': 2617.912}, {'period': '2007-01-28', 'v': 2006.919}, {'period': '2006-01-29', 'v': 1495.992}, {'period': '2005-01-30', 'v': 1221.091}, {'period': '2004-01-25', 'v': 1051.185}, {'period': '2003-01-26', 'v': 932.687}, {'period': '2002-01-27', 'v': 763.819}, {'period': '2001-01-28', 'v': 407.107}, {'period': '2000-01-30', 'v': 124.563}], 'cashRatio': [{'period': '2026-01-25', 'v': 0.32972670459845166}, {'period': '2025-01-26', 'v': 0.47592397628414695}, {'period': '2024-01-28', 'v': 0.6847897657793246}, {'period': '2023-01-29', 'v': 0.516379704403474}, {'period': '2022-01-30', 'v': 0.4590542099192618}, {'period': '2021-01-31', 'v': 0.21579617834394904}, {'period': '2020-01-26', 'v': 6.1076233183856505}, {'period': '2019-01-27', 'v': 0.5884123401053424}, {'period': '2018-01-28', 'v': 3.470945359930616}, {'period': '2017-01-29', 'v': 0.9876957494407159}, {'period': '2016-01-31', 'v': 0.2535091450446618}, {'period': '2015-01-25', 'v': 0.5546875}, {'period': '2014-01-26', 'v': 1.2179713081811028}, {'period': '2013-01-27', 'v': 0.7506338203463757}, {'period': '2012-01-29', 'v': 0.7181786704345787}, {'period': '2011-01-30', 'v': 0.7058170199494633}, {'period': '2010-01-31', 'v': 0.570160050383871}, {'period': '2009-01-25', 'v': 0.5364665145114701}, {'period': '2008-01-27', 'v': 0.7516525170059588}, {'period': '2007-01-28', 'v': 0.852235495227823}, {'period': '2006-01-29', 'v': 1.2578244148643936}, {'period': '2005-01-30', 'v': 0.49509445431146654}, {'period': '2004-01-25', 'v': 0.6417668326788621}, {'period': '2003-01-26', 'v': 0.91447049398073}, {'period': '2002-01-27', 'v': 0.7681767221691649}, {'period': '2001-01-28', 'v': 2.179178907429133}, {'period': '2000-01-30', 'v': 0.8076090521482454}, {'period': '1999-01-31', 'v': 1.0663936513325412}, {'period': '1998-01-31', 'v': 0.40311016863576693}, {'period': '1997-12-31', 'v': 0.40311365454433573}, {'period': '1996-12-31', 'v': 0.8093515887367605}], 'currentRatio': [{'period': '2026-01-25', 'v': 3.9053}, {'period': '2025-01-26', 'v': 4.4399}, {'period': '2024-01-28', 'v': 4.1713}, {'period': '2023-01-29', 'v': 3.5156}, {'period': '2022-01-30', 'v': 6.6503}, {'period': '2021-01-31', 'v': 4.0904}, {'period': '2020-01-26', 'v': 7.6738}, {'period': '2019-01-27', 'v': 7.9436}, {'period': '2018-01-28', 'v': 8.0269}, {'period': '2017-01-29', 'v': 4.774}, {'period': '2016-01-31', 'v': 2.5746}, {'period': '2015-01-25', 'v': 6.3761}, {'period': '2014-01-26', 'v': 5.949}, {'period': '2013-01-27', 'v': 4.8916}, {'period': '2012-01-29', 'v': 4.1995}, {'period': '2011-01-30', 'v': 3.4232}, {'period': '2010-01-31', 'v': 3.1628}, {'period': '2009-01-25', 'v': 2.7845}, {'period': '2008-01-27', 'v': 2.9869}, {'period': '2007-01-28', 'v': 3.1806}, {'period': '2006-01-29', 'v': 3.5342}, {'period': '2005-01-30', 'v': 3.1031}, {'period': '2004-01-25', 'v': 3.1508}, {'period': '2003-01-26', 'v': 3.562}, {'period': '2002-01-27', 'v': 2.8469}, {'period': '2001-01-28', 'v': 3.0085}, {'period': '2000-01-30', 'v': 2.2719}, {'period': '1999-01-31', 'v': 2.1455}, {'period': '1998-01-31', 'v': 1.2369}, {'period': '1997-12-31', 'v': 1.1901}, {'period': '1996-12-31', 'v': 1.1051}], 'ebitPerShare': [{'period': '2026-01-25', 'v': 5.3189}, {'period': '2025-01-26', 'v': 3.2839}, {'period': '2024-01-28', 'v': 1.3221}, {'period': '2023-01-29', 'v': 0.1685}, {'period': '2022-01-30', 'v': 0.3961}, {'period': '2021-01-31', 'v': 0.1804}, {'period': '2020-01-26', 'v': 0.1151}, {'period': '2019-01-27', 'v': 0.1522}, {'period': '2018-01-28', 'v': 0.127}, {'period': '2017-01-29', 'v': 0.0745}, {'period': '2016-01-31', 'v': 0.0328}, {'period': '2015-01-25', 'v': 0.0337}, {'period': '2014-01-26', 'v': 0.0209}, {'period': '2013-01-27', 'v': 0.0259}, {'period': '2012-01-29', 'v': 0.0263}, {'period': '2011-01-30', 'v': 0.0109}, {'period': '2010-01-31', 'v': -0.0045}, {'period': '2009-01-25', 'v': -0.0032}, {'period': '2008-01-27', 'v': 0.0345}, {'period': '2007-01-28', 'v': 0.0193}, {'period': '2006-01-29', 'v': 0.0153}, {'period': '2005-01-30', 'v': 0.0045}, {'period': '2004-01-25', 'v': 0.0018}, {'period': '2003-01-26', 'v': 0.0071}, {'period': '2002-01-27', 'v': 0.0118}, {'period': '2001-01-28', 'v': 0.0067}, {'period': '2000-01-30', 'v': 0.0034}, {'period': '1999-01-31', 'v': 0.0003}, {'period': '1997-12-31', 'v': -0.0006}, {'period': '1996-12-31', 'v': -0.0005}, {'period': '1995-12-31', 'v': -0.0012}, {'period': '1994-12-31', 'v': -0.0004}, {'period': '1993-12-31', 'v': -0.0002}], 'ebitda': [{'period': '2026-01-25', 'v': 133230}, {'period': '2025-01-26', 'v': 83317}, {'period': '2024-01-28', 'v': 34480}, {'period': '2023-01-29', 'v': 5768}, {'period': '2022-01-30', 'v': 11215}, {'period': '2021-01-31', 'v': 5630}, {'period': '2020-01-26', 'v': 3227}, {'period': '2019-01-27', 'v': 4066}, {'period': '2018-01-28', 'v': 3409}, {'period': '2017-01-29', 'v': 2121}, {'period': '2016-01-31', 'v': 944}, {'period': '2015-01-25', 'v': 979.114}, {'period': '2014-01-26', 'v': 735.375}, {'period': '2013-01-27', 'v': 874.474}, {'period': '2012-01-29', 'v': 852.504}, {'period': '2011-01-30', 'v': 442.736}, {'period': '2010-01-31', 'v': 97.719}, {'period': '2009-01-25', 'v': 114.323}, {'period': '2008-01-27', 'v': 969.538}, {'period': '2007-01-28', 'v': 561.014}, {'period': '2006-01-29', 'v': 434.64099999999996}, {'period': '2005-01-30', 'v': 197.773}, {'period': '2004-01-25', 'v': 118.664}, {'period': '2003-01-26', 'v': 143.986}, {'period': '2002-01-27', 'v': 251.825}, {'period': '2001-01-28', 'v': 128.135}, {'period': '2000-01-30', 'v': 67.62299999999999}, {'period': '1999-01-31', 'v': 8.522}, {'period': '1997-12-31', 'v': -2.096}, {'period': '1996-12-31', 'v': -2.191}, {'period': '1995-12-31', 'v': -5.946}], 'eps': [{'period': '2026-01-25', 'v': 4.8979}, {'period': '2025-01-26', 'v': 2.9382}, {'period': '2024-01-28', 'v': 1.1933}, {'period': '2023-01-29', 'v': 0.1742}, {'period': '2022-01-30', 'v': 0.3847}, {'period': '2021-01-31', 'v': 0.1725}, {'period': '2020-01-26', 'v': 0.1131}, {'period': '2019-01-27', 'v': 0.1656}, {'period': '2018-01-28', 'v': 0.1205}, {'period': '2017-01-29', 'v': 0.0642}, {'period': '2016-01-31', 'v': 0.027}, {'period': '2015-01-25', 'v': 0.028}, {'period': '2014-01-26', 'v': 0.0185}, {'period': '2013-01-27', 'v': 0.0225}, {'period': '2012-01-29', 'v': 0.0236}, {'period': '2011-01-30', 'v': 0.0108}, {'period': '2010-01-31', 'v': -0.0031}, {'period': '2009-01-25', 'v': -0.0014}, {'period': '2008-01-27', 'v': 0.0329}, {'period': '2007-01-28', 'v': 0.0191}, {'period': '2006-01-29', 'v': 0.0137}, {'period': '2005-01-30', 'v': 0.0042}, {'period': '2004-01-25', 'v': 0.0024}, {'period': '2003-01-26', 'v': 0.0045}, {'period': '2002-01-27', 'v': 0.0086}, {'period': '2001-01-28', 'v': 0.0052}, {'period': '2000-01-30', 'v': 0.0024}, {'period': '1999-01-31', 'v': 0.0003}, {'period': '1997-12-31', 'v': -0.0006}, {'period': '1996-12-31', 'v': -0.0006}, {'period': '1995-12-31', 'v': -0.0012}, {'period': '1994-12-31', 'v': -0.0004}, {'period': '1993-12-31', 'v': -0.0001}], 'ev': [{'period': '2026-01-25', 'v': 4529084}, {'period': '2025-01-26', 'v': 2899979.8}, {'period': '2024-01-28', 'v': 1545314.5}, {'period': '2023-01-29', 'v': 478949.2}, {'period': '2022-01-30', 'v': 621106}, {'period': '2021-01-31', 'v': 333864}, {'period': '2020-01-26', 'v': 138097}, {'period': '2019-01-27', 'v': 85392.1}, {'period': '2018-01-28', 'v': 147589}, {'period': '2017-01-29', 'v': 59910.7}, {'period': '2016-01-31', 'v': 16677.4}, {'period': '2015-01-25', 'v': 12106}, {'period': '2014-01-26', 'v': 9011.848}, {'period': '2013-01-27', 'v': 7165.582}, {'period': '2012-01-29', 'v': 8391.233}, {'period': '2011-01-30', 'v': 13255.528}, {'period': '2010-01-31', 'v': 8771.919}, {'period': '2009-01-25', 'v': 3888.336}, {'period': '2008-01-27', 'v': 12967.831}, {'period': '2007-01-28', 'v': 10185.886}, {'period': '2006-01-29', 'v': 7276.134}, {'period': '2005-01-30', 'v': 3601.944}, {'period': '2004-01-25', 'v': 3682.599}, {'period': '2003-01-26', 'v': 1543.272}, {'period': '2002-01-27', 'v': 9806.327}, {'period': '2001-01-28', 'v': 3093.301}, {'period': '2000-01-30', 'v': 1094.338}], 'evEbitda': [{'period': '2026-01-25', 'v': 33.9945}, {'period': '2025-01-26', 'v': 34.8066}, {'period': '2024-01-28', 'v': 44.8177}, {'period': '2023-01-29', 'v': 83.0356}, {'period': '2022-01-30', 'v': 55.3817}, {'period': '2021-01-31', 'v': 59.3009}, {'period': '2020-01-26', 'v': 42.7942}, {'period': '2019-01-27', 'v': 21.0015}, {'period': '2018-01-28', 'v': 43.2939}, {'period': '2017-01-29', 'v': 28.2464}, {'period': '2016-01-31', 'v': 17.6667}, {'period': '2015-01-25', 'v': 12.3642}, {'period': '2014-01-26', 'v': 12.2548}, {'period': '2013-01-27', 'v': 8.1942}, {'period': '2012-01-29', 'v': 9.843}, {'period': '2011-01-30', 'v': 29.94}, {'period': '2010-01-31', 'v': 89.7668}, {'period': '2009-01-25', 'v': 34.0118}, {'period': '2008-01-27', 'v': 13.3753}, {'period': '2007-01-28', 'v': 18.1562}, {'period': '2006-01-29', 'v': 16.7406}, {'period': '2005-01-30', 'v': 18.2125}, {'period': '2004-01-25', 'v': 31.0338}, {'period': '2003-01-26', 'v': 10.7182}, {'period': '2002-01-27', 'v': 38.941}, {'period': '2001-01-28', 'v': 24.141}, {'period': '2000-01-30', 'v': 16.1829}], 'evRevenue': [{'period': '2026-01-25', 'v': 20.974}, {'period': '2025-01-26', 'v': 22.2226}, {'period': '2024-01-28', 'v': 25.3655}, {'period': '2023-01-29', 'v': 17.756}, {'period': '2022-01-30', 'v': 23.0774}, {'period': '2021-01-31', 'v': 20.0218}, {'period': '2020-01-26', 'v': 12.6486}, {'period': '2019-01-27', 'v': 7.2885}, {'period': '2018-01-28', 'v': 15.1934}, {'period': '2017-01-29', 'v': 8.6701}, {'period': '2016-01-31', 'v': 3.3288}, {'period': '2015-01-25', 'v': 2.5859}, {'period': '2014-01-26', 'v': 2.182}, {'period': '2013-01-27', 'v': 1.6741}, {'period': '2012-01-29', 'v': 2.0989}, {'period': '2011-01-30', 'v': 3.741}, {'period': '2010-01-31', 'v': 2.637}, {'period': '2009-01-25', 'v': 1.1353}, {'period': '2008-01-27', 'v': 3.1645}, {'period': '2007-01-28', 'v': 3.3192}, {'period': '2006-01-29', 'v': 3.0627}, {'period': '2005-01-30', 'v': 1.792}, {'period': '2004-01-25', 'v': 2.0201}, {'period': '2003-01-26', 'v': 0.8082}, {'period': '2002-01-27', 'v': 7.1607}, {'period': '2001-01-28', 'v': 4.2071}, {'period': '2000-01-30', 'v': 2.9221}], 'fcfMargin': [{'period': '2026-01-25', 'v': 0.4477}, {'period': '2025-01-26', 'v': 0.4663}, {'period': '2024-01-28', 'v': 0.4435}, {'period': '2023-01-29', 'v': 0.1412}, {'period': '2022-01-30', 'v': 0.3021}, {'period': '2021-01-31', 'v': 0.2815}, {'period': '2020-01-26', 'v': 0.3913}, {'period': '2019-01-27', 'v': 0.2683}, {'period': '2018-01-28', 'v': 0.2995}, {'period': '2017-01-29', 'v': 0.2165}, {'period': '2016-01-31', 'v': 0.2174}, {'period': '2015-01-25', 'v': 0.1673}, {'period': '2014-01-26', 'v': 0.1404}, {'period': '2013-01-27', 'v': 0.1497}, {'period': '2012-01-29', 'v': 0.1927}, {'period': '2011-01-30', 'v': 0.1631}, {'period': '2010-01-31', 'v': 0.1233}, {'period': '2008-01-27', 'v': 0.2642}, {'period': '2007-01-28', 'v': 0.144}, {'period': '2006-01-29', 'v': 0.1544}, {'period': '2005-01-30', 'v': 0.0323}, {'period': '2003-01-26', 'v': 0.1057}, {'period': '2002-01-27', 'v': 0.0466}, {'period': '2001-01-28', 'v': 0.315}, {'period': '2000-01-30', 'v': 0.0114}], 'grossMargin': [{'period': '2026-01-25', 'v': 0.7315}, {'period': '2025-01-26', 'v': 0.7499}, {'period': '2024-01-28', 'v': 0.7272}, {'period': '2023-01-29', 'v': 0.5693}, {'period': '2022-01-30', 'v': 0.6493}, {'period': '2021-01-31', 'v': 0.6234}, {'period': '2020-01-26', 'v': 0.6199}, {'period': '2019-01-27', 'v': 0.6121}, {'period': '2018-01-28', 'v': 0.5993}, {'period': '2017-01-29', 'v': 0.588}, {'period': '2016-01-31', 'v': 0.5611}, {'period': '2015-01-25', 'v': 0.5553}, {'period': '2014-01-26', 'v': 0.5491}, {'period': '2013-01-27', 'v': 0.5202}, {'period': '2012-01-29', 'v': 0.5144}, {'period': '2011-01-30', 'v': 0.3977}, {'period': '2010-01-31', 'v': 0.3538}, {'period': '2009-01-25', 'v': 0.3429}, {'period': '2008-01-27', 'v': 0.4562}, {'period': '2007-01-28', 'v': 0.4238}, {'period': '2006-01-29', 'v': 0.3831}, {'period': '2005-01-30', 'v': 0.3222}, {'period': '2004-01-25', 'v': 0.2881}, {'period': '2003-01-26', 'v': 0.3017}, {'period': '2002-01-27', 'v': 0.3792}, {'period': '2001-01-28', 'v': 0.3711}, {'period': '2000-01-30', 'v': 0.3787}, {'period': '1999-01-31', 'v': 0.3064}, {'period': '1997-12-31', 'v': 0.2692}, {'period': '1996-12-31', 'v': 0.2234}, {'period': '1995-12-31', 'v': -0.3105}], 'inventoryTurnover': [{'period': '2026-01-25', 'v': 3.6829}, {'period': '2025-01-26', 'v': 4.2493}, {'period': '2024-01-28', 'v': 3.1838}, {'period': '2023-01-29', 'v': 2.9928}, {'period': '2022-01-30', 'v': 4.2604}, {'period': '2021-01-31', 'v': 4.477}, {'period': '2020-01-26', 'v': 3.2498}, {'period': '2019-01-27', 'v': 3.8338}, {'period': '2018-01-28', 'v': 4.8956}, {'period': '2017-01-29', 'v': 4.698}, {'period': '2016-01-31', 'v': 4.8812}, {'period': '2015-01-25', 'v': 4.7821}, {'period': '2014-01-26', 'v': 4.6546}, {'period': '2013-01-27', 'v': 5.4567}, {'period': '2012-01-29', 'v': 5.6616}, {'period': '2011-01-30', 'v': 6.3124}, {'period': '2010-01-31', 'v': 4.9499}, {'period': '2009-01-25', 'v': 5.0216}, {'period': '2008-01-27', 'v': 6.2495}, {'period': '2007-01-28', 'v': 5.8021}, {'period': '2006-01-29', 'v': 5.1367}, {'period': '2005-01-30', 'v': 4.9542}, {'period': '2004-01-25', 'v': 6.8428}, {'period': '2003-01-26', 'v': 7.4302}, {'period': '2002-01-27', 'v': 5.5889}, {'period': '2001-01-28', 'v': 7.2241}, {'period': '2000-01-30', 'v': 7.0233}, {'period': '1999-01-31', 'v': 7.5313}], 'longtermDebtTotalAsset': [{'period': '2026-01-25', 'v': 0.0361}, {'period': '2025-01-26', 'v': 0.0758}, {'period': '2024-01-28', 'v': 0.1287}, {'period': '2023-01-29', 'v': 0.2356}, {'period': '2022-01-30', 'v': 0.2477}, {'period': '2021-01-31', 'v': 0.2071}, {'period': '2020-01-26', 'v': 0.115}, {'period': '2019-01-27', 'v': 0.1496}, {'period': '2018-01-28', 'v': 0.1766}, {'period': '2017-01-29', 'v': 0.2047}, {'period': '2016-01-31', 'v': 0.0118}, {'period': '2015-01-25', 'v': 0.1922}, {'period': '2014-01-26', 'v': 0.1871}, {'period': '2013-01-27', 'v': 0}, {'period': '2004-01-25', 'v': 0}, {'period': '2003-01-26', 'v': 0.1855}, {'period': '2002-01-27', 'v': 0.1996}, {'period': '2001-01-28', 'v': 0.295}, {'period': '2000-01-30', 'v': 0.0025}], 'longtermDebtTotalCapital': [{'period': '2026-01-25', 'v': 0.0451}, {'period': '2025-01-26', 'v': 0.0964}, {'period': '2024-01-28', 'v': 0.1606}, {'period': '2023-01-29', 'v': 0.2935}, {'period': '2022-01-30', 'v': 0.2914}, {'period': '2021-01-31', 'v': 0.25}, {'period': '2020-01-26', 'v': 0.1403}, {'period': '2019-01-27', 'v': 0.1755}, {'period': '2018-01-28', 'v': 0.2096}, {'period': '2017-01-29', 'v': 0.2348}, {'period': '2016-01-31', 'v': 0.0146}, {'period': '2015-01-25', 'v': 0.238}, {'period': '2014-01-26', 'v': 0.2326}, {'period': '2013-01-27', 'v': 0}, {'period': '2004-01-25', 'v': 0}, {'period': '2003-01-26', 'v': 0.2413}, {'period': '2002-01-27', 'v': 0.2794}, {'period': '2001-01-28', 'v': 0.4237}, {'period': '2000-01-30', 'v': 0.0039}], 'longtermDebtTotalEquity': [{'period': '2026-01-25', 'v': 0.0475}, {'period': '2025-01-26', 'v': 0.1067}, {'period': '2024-01-28', 'v': 0.1968}, {'period': 

In [5]:
#Selskaps profil
profile = finnhub_client.company_profile2(symbol="NVDA")
print(profile)

#Dette gir meg ting som markedsverdi, sektor, land, børs, antall utestående aksjer, short interest osv. Dette er ting som kan være nyttig for å lage en regresjonsmodell.

{'ticker': 'NVDA', 'name': 'NVIDIA Corp', 'country': 'US', 'currency': 'USD', 'estimateCurrency': 'USD', 'exchange': 'NASDAQ NMS - GLOBAL MARKET', 'ipo': '1999-01-22', 'marketCapitalization': 5260789.014704283, 'logo': 'https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/942959144056.png', 'shareOutstanding': 24200, 'finnhubIndustry': 'Semiconductors', 'phone': '13026365401', 'weburl': 'https://www.nvidia.com/', 'floatingShare': 23228.1}

In [6]:
#Gjør det til en pandas dataframe for enklere dataanalyse

metrics = data["metric"]
df.fundamentals = pd.DataFrame(list(metrics.items()), columns=["Nøkkeltall", "Verdi"])
df.fundamentals

C:\Users\lukat\AppData\Local\Temp\ipykernel_18148\2103141244.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.fundamentals = pd.DataFrame(list(metrics.items()), columns=["Nøkkeltall", "Verdi"])

                             Nøkkeltall      Verdi
0             10DayAverageTradingVolume  125.74631
1                13WeekPriceReturnDaily     8.9163
2                26WeekPriceReturnDaily    19.5127
3                     3MonthADReturnStd    40.5757
4            3MonthAverageTradingVolume  144.10357
..                                  ...        ...
128  tangibleBookValuePerShareQuarterly     9.3588
129                           tbvCagr5Y      61.18
130         totalDebt/totalEquityAnnual     0.0538
131      totalDebt/totalEquityQuarterly     0.1457
132          yearToDatePriceReturnDaily    17.0456

[133 rows x 2 columns]

In [7]:
#Velge nøkkeltall man trenger selv (Hva som kan være nyttig for å lage en regresjonsmodell for NVIDIA)
fundamentals_metrics = ["peNormalizedAnnual", "roeTTM", "netProfitMarginTTM",  "currentRatioAnnual",  "grossMarginTTM"]
for n in fundamentals_metrics:
    print(n, ":", metrics.get(n))

peNormalizedAnnual : 43.8154
roeTTM : 110.11
netProfitMarginTTM : 63.66
currentRatioAnnual : 3.9053
grossMarginTTM : 74.67

In [8]:
#Dette er en kombinert datasett for en samlet tabell bare for finnhub verdiene
fundamental_metrics = ["peTTM", "roeTTM", "netMargin", "currentRatio", "grossMargin"]

fundamentals = {}

for metric in fundamental_metrics:
    entries = quarterly_series.get(metric, [])
    for entry in entries:
        date = entry["period"]
        value = entry["v"]
        fundamentals.setdefault(date, {})[metric] = value

df_fundamentals = pd.DataFrame.from_dict(fundamentals, orient="index")
df_fundamentals.index = pd.to_datetime(df_fundamentals.index)
df_fundamentals = df_fundamentals.sort_index()

df_fundamentals

              peTTM  roeTTM  netMargin  currentRatio  grossMargin
1997-03-30      NaN     NaN   -18.0923           NaN      -2.2000
1997-06-29      NaN     NaN  -210.8333           NaN     -24.0000
1997-09-28      NaN     NaN    -0.4705           NaN       0.1679
1997-12-31      NaN     NaN     0.0605           NaN       0.3058
1998-04-26      NaN     NaN    -0.0361           NaN       0.2615
...             ...     ...        ...           ...          ...
2025-07-27  49.8020  1.0522     0.5653        4.2140       0.7242
2025-10-26  46.9083  1.0382     0.5598        4.4676       0.7341
2026-01-25  37.7391  1.0437     0.6306        3.9053       0.7500
2026-04-26  32.9774  1.1166     0.7146        3.4408       0.7493
2026-07-26  24.6556  1.1011     0.6203        4.5889       0.7498

[118 rows x 5 columns]

TABELLEN KOMBINERTE DATASETT UNDER

In [9]:
# Gjør klar df (markedsdata) for merge
df_market = df.reset_index()
df_market['timestamp'] = pd.to_datetime(df_market['timestamp']).dt.tz_localize(None)

# Gjør klar df_fundamentals for merge
df_fund = df_fundamentals.reset_index().rename(columns={'index': 'timestamp'})
df_fund['timestamp'] = pd.to_datetime(df_fund['timestamp'])

# Sorter begge på timestamp (påkrevd for merge_asof)
df_market = df_market.sort_values('timestamp')
df_fund = df_fund.sort_values('timestamp')

# Koble sammen: for hver handelsdag, hent siste kjente fundamentalverdi
df_combined = pd.merge_asof(df_market, df_fund, on='timestamp', direction='backward')

df_combined

,symbol,timestamp,open,high,low,close,volume,trade_count,vwap,peTTM,roeTTM,netMargin,currentRatio,grossMargin
0,NVDA,2026-01-02 05:00:00,189.835,192.9299,188.26,188.85,148240462.0,2260604.0,189.912199,46.9083,1.0382,0.5598,4.4676,0.7341
1,NVDA,2026-01-05 05:00:00,191.760,193.6300,186.15,188.12,182965768.0,2574019.0,188.757392,46.9083,1.0382,0.5598,4.4676,0.7341
2,NVDA,2026-01-06 05:00:00,190.520,192.1740,186.82,187.24,176862604.0,2519447.0,189.058048,46.9083,1.0382,0.5598,4.4676,0.7341
3,NVDA,2026-01-07 05:00:00,188.570,191.3700,186.56,189.11,153543174.0,2292255.0,189.527040,46.9083,1.0382,0.5598,4.4676,0.7341
4,NVDA,2026-01-08 05:00:00,189.110,189.5500,183.71,185.04,172457048.0,2521746.0,185.358816,46.9083,1.0382,0.5598,4.4676,0.7341
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,NVDA,2026-09-08 04:00:00,233.110,233.7100,224.85,225.73,123863958.0,2405736.0,227.183114,24.6556,1.1011,0.6203,4.5889,0.7498
171,NVDA,2026-09-09 04:00:00,225.275,226.1800,223.46,223.67,83765394.0,1827357.0,224.230606,24.6556,1.1011,0.6203,4.5889,0.7498
172,NVDA,2026-09-10 04:00:00,220.525,220.9900,217.20,218.36,106720602.0,2202079.0,218.423135,24.6556,1.1011,0.6203,4.5889,0.7498
173,NVDA,2026-09-11 04:00:00,221.235,222.0000,218.15,218.29,90036579.0,2013738.0,219.556789,24.6556,1.1011,0.6203,4.5889,0.7498
174,NVDA,2026-09-14 04:00:00,211.240,212.3900,208.93,212.20,77067681.0,1987583.0,210.863471,24.6556,1.1011,0.6203,4.5889,0.7498

In [10]:
delta = df_combined["close"].diff()

gain = delta.where(delta > 0, 0)
loss = -delta.where(delta < 0, 0)

avg_gain = gain.rolling(window=14).mean()
avg_loss = loss.rolling(window=14).mean()

rs = avg_gain / avg_loss

df_combined["rsi14"] = 100 - (100 / (1 + rs))

px.line(
    df_combined.reset_index().dropna(),
    x="timestamp",
    y="rsi14",
    title="NVDA RSI14"
).show()

In [11]:
sma20 = df_combined["close"].rolling(window=20).mean()
std20 = df_combined["close"].rolling(window=20).std()

df_combined["upper_band"] = sma20 + (std20 * 2)
df_combined["lower_band"] = sma20 - (std20 * 2)

px.line(
    df_combined.reset_index().dropna(),
    x="timestamp",
    y=["close", "upper_band", "lower_band"],
    title="NVDA Bollinger Bands"
).show()

In [12]:
high_low = df_combined["high"] - df_combined["low"]
high_close = abs(df_combined["high"] - df_combined["close"].shift(1))
low_close = abs(df_combined["low"] - df_combined["close"].shift(1))

tr = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)

df_combined["atr14"] = tr.rolling(window=14).mean()

px.line(
    df_combined.reset_index().dropna(),
    x="timestamp",
    y= "atr14",
    title="NVDA ATR14"
).show()

In [13]:
#Gjennomsnittprisen over en bestemt periode

df_combined["sma50"] = df_combined["close"].rolling(window=50).mean()
df_combined["sma100"] = df_combined["close"].rolling(window=100).mean()

px.line(
    df_combined.reset_index(),
    x="timestamp",
    y=["close", "sma50", "sma100"],
    title="NVDA Close Price with SMA50 and SMA100"
).show()

In [14]:
df_combined.isna().sum()

symbol           0
timestamp        0
open             0
high             0
low              0
close            0
volume           0
trade_count      0
vwap             0
peTTM            0
roeTTM           0
netMargin        0
currentRatio     0
grossMargin      0
rsi14           13
upper_band      19
lower_band      19
atr14           13
sma50           49
sma100          99
dtype: int64

In [15]:
df_combined = df_combined.dropna()

In [16]:
df_combined.describe()

,timestamp,open,high,low,close,volume,trade_count,vwap,peTTM,roeTTM,netMargin,currentRatio,grossMargin,rsi14,upper_band,lower_band,atr14,sma50,sma100
count,76,76.000000,76.000000,76.000000,76.000000,7.600000e+01,7.600000e+01,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000
mean,2026-07-20 18:31:34.736842,211.229875,214.146253,207.724522,210.739342,1.400003e+08,2.450962e+06,210.837832,29.144992,1.109462,0.671172,3.969530,0.749530,50.295105,225.461181,195.598569,7.400346,207.648176,200.426422
min,2026-05-27 04:00:00,192.370000,195.550000,189.800000,190.010000,7.650232e+07,1.741900e+06,192.174850,24.655600,1.101100,0.620300,3.440800,0.749300,32.673118,212.827655,188.297090,5.438407,198.087600,191.741300
25%,2026-06-23 22:00:00,203.982500,207.182500,199.490000,203.467500,1.136204e+08,2.160200e+06,203.070047,24.655600,1.101100,0.620300,3.440800,0.749300,42.001052,216.417926,189.758867,6.801289,206.265850,196.104775
50%,2026-07-21 16:00:00,211.210000,213.330000,207.270000,211.050000,1.351393e+08,2.394993e+06,210.221473,32.977400,1.116600,0.714600,3.440800,0.749300,49.700314,226.659831,191.590305,7.588636,208.314100,199.028050
75%,2026-08-17 10:00:00,220.468750,222.205000,216.490000,218.307500,1.545439e+08,2.607926e+06,219.340525,32.977400,1.116600,0.714600,4.588900,0.749800,57.458130,232.465868,200.056251,7.874802,209.751850,204.885250
max,2026-09-14 04:00:00,233.110000,234.760000,229.630000,230.360000,2.996411e+08,4.707580e+06,231.817409,32.977400,1.116600,0.714600,4.588900,0.749800,77.411027,235.915069,208.608221,8.757064,212.931400,211.363700
std,NaN,10.447244,10.197314,10.439210,10.007226,4.121744e+07,4.477871e+05,10.136401,4.175474,0.007777,0.047315,0.576061,0.000251,10.518190,7.922884,7.037516,0.786132,3.041152,5.699839

In [17]:
corr = df_combined.corr(numeric_only=True)

px.imshow(
    corr,
    zmin=-1,
    zmax=1,
    text_auto=".2f",
    color_continuous_scale="RdBu_r",
    title = "Correlation Matrix"
).show()

In [18]:
df_combined = df_combined.reset_index()

px.line(
    df_combined,
    x="timestamp",
    y="close",
    title="NVDA Closing Prices",
).show()

In [19]:
returns = df_combined["close"].pct_change().dropna()
px.histogram(
    returns,
    nbins=20,
    title="NVDA Daily Returns Distribution",).show()

In [20]:
px.box(
    returns,
    title="NVDA Daily Returns Box Plot"
).show()

In [21]:
go.Figure(go.Candlestick(
    x=df_combined["timestamp"],
    open=df_combined["open"],
    high=df_combined["high"],
    low=df_combined["low"],
    close=df_combined["close"],
)).show()

In [22]:
df_combined["target"] = df_combined["close"].shift(-1) / df_combined["close"] - 1

# Fjern siste rad, som mangler target
df_combined = df_combined.dropna(subset=["target"]) #fjerner siste rad som inneholder NaN i target-kolonnen

df_combined[["timestamp", "close", "target"]].tail(10)

             timestamp   close    target
65 2026-08-28 04:00:00  217.55  0.014847
66 2026-08-31 04:00:00  220.78 -0.015128
67 2026-09-01 04:00:00  217.44  0.032055
68 2026-09-02 04:00:00  224.41  0.018003
69 2026-09-03 04:00:00  228.45  0.008361
70 2026-09-04 04:00:00  230.36 -0.020099
71 2026-09-08 04:00:00  225.73 -0.009126
72 2026-09-09 04:00:00  223.67 -0.023740
73 2026-09-10 04:00:00  218.36 -0.000321
74 2026-09-11 04:00:00  218.29 -0.027899

Del datasettet i test- og treningsdata basert på tidsrekkefølge

In [23]:
split = int(len(df_combined) * 0.8) # finner hvor 80% grensen er

train_df = df_combined.iloc[:split] # De første ELDSTE 80% av dagene
test_df = df_combined.iloc[split:]  # De siste nyeste 20% av dagene

X_train = train_df.drop(columns=['target', "symbol", "timestamp"])      #features for trening
y_train = train_df['target']                      #fasit for trening

X_test = test_df.drop(columns=['target', "symbol", "timestamp"])         #features for test
y_test = test_df['target']                        #fasit for test

Tren en regresjonsmodell, for eksempel lineær regresjon.
o Eller SVR for en smule mer utfordring

In [24]:
model = LinearRegression() #oppretter modellen
model.fit(X_train, y_train) # "lærer" mønsteret på treningsdataene

y_pred = model.predict(X_test) #bruker det lærte mønsteret til å predikere på testdataene

In [ ]:
Evaluer modellen ved hjelp av mål som MAE, RMSE og R².

In [25]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)  # Calculate RMSE from MSE
r2 = r2_score(y_test, y_pred)

print(f"Mål: MAE, Verdi: {mae}")
print(f"Mål: RMSE, Verdi: {rmse}")
print(f"Mål: R², Verdi: {r2}")

Mål: MAE, Verdi: 0.024445447674195705
Mål: RMSE, Verdi: 0.03148830650492399
Mål: R², Verdi: 0.00883240266070251

In [28]:
viktig = pd.DataFrame({
    "feature": X_train.columns,
    "coefficient": model.coef_
}).sort_values(by="coefficient", key=abs, ascending=False)

viktig

         feature   coefficient
6    trade_count -3.739618e-09
5         volume  6.752495e-11
13         rsi14  5.053251e-14
3            low  3.702797e-14
4          close  2.973271e-14
7           vwap  2.970410e-14
0          index  2.382129e-14
1           open  1.918767e-14
2           high  1.766271e-14
15    lower_band -1.590573e-14
14    upper_band  1.378120e-14
18        sma100  7.128507e-15
17         sma50  3.027996e-15
16         atr14 -2.493856e-15
8          peTTM  1.227254e-15
11  currentRatio -1.693156e-16
10     netMargin  1.390686e-17
9         roeTTM  2.285857e-18
12   grossMargin -7.373731e-20

In [31]:
# Lag en dataframe med faktisk og predikert avkastning for testperioden
pred_df = pd.DataFrame({
    "timestamp": test_df["timestamp"].values,
    "faktisk_avkastning": y_test.values,
    "predikert_avkastning": y_pred
})

# Linjegraf: faktisk vs. predikert avkastning over tid
px.line(
    pred_df,
    x="timestamp",
    y=["faktisk_avkastning", "predikert_avkastning"],
    title="NVDA: Faktisk vs. Predikert Avkastning (testdata)"
).show()